name: Lint Code Base

on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [main, master]

jobs:
  super-linter:
    name: Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super Linter
        uses: super-linter/super-linter@v8.0.0
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CHECKOV: false
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN: false
          VALIDATE_YAML_PRETTIER: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
